### ISSUE TITLE
Can you provide your experience with json and roundup front ends?

### ISSUE THREAD

**Issue by rouilj** [s1341/roundup-json#1]
Hello:

I notice that you are using a json end point with roundup.

The current development version of roundup includes a REST interface.
Would you be willing to comment on it and compare it to what the json endpoint
provides? The goal here is to provide a REST interface that is usable for dynamic
front ends and it looks like you have some experience with that.

You can see the current doc at:

   https://github.com/roundup-tracker/roundup/blob/master/doc/rest.txt

Also have you done any more work on the tracker?

Thanks and have a great week.

-- rouilj

**Comment by s1341** [comment]
I was using this for code which I no longer have access to. It is effectively abandonware. Sorry.
